compress: true
javascripts:
  jquery: &jquery
    - javascripts/jquery/jquery-3.2.1.js
    - javascripts/jquery/jquery-ui-1.12.1.js
    - javascripts/jquery/jquery-ui-timepicker-1.6.3.js
    - javascripts/jquery/jquery.multi-select-0.9.12.js
    - javascripts/jquery/jquery.scrollTo-2.1.2.js
    - javascripts/jquery/jquery.ui.touch-punch-0.2.3.js

    - javascripts/studip-jquery-tweaks.js
    - javascripts/studip-jquery.multi-select.tweaks.js

  modernizr: &modernizr
    - javascripts/vendor/modernizr-3.5.0.js

  highlight: &highlight
    - javascripts/vendor/highlight-9.12.0.js

  header: &header
    - javascripts/vendor/favico.js-0.3.10.js
    - javascripts/header.js
    - javascripts/header-navigation.js
    - javascripts/personal_notifications.js

  toolbar: &toolbar
    - javascripts/toolbar.js
    - javascripts/toolbar-buttonset.js
    - javascripts/smiley-picker.js

  wysiwyg: &wysiwyg
    - javascripts/jquery/jquery.fileupload-9.19.1.js
    - javascripts/jquery/jquery.iframe-transport-9.19.1.js
    - javascripts/ckeditor/ckeditor.js
    - javascripts/wysiwyg.js

  dialog: &dialog
    - javascripts/studip-overlay.js
    - javascripts/studip-dialog.js

  sidebar: &sidebar
    - javascripts/jquery/jquery.sticky-kit.1.1.2.js
    - javascripts/sidebar.js

  statusgroups: &statusgroups
    - javascripts/statusgroups.js
    - javascripts/jquery/jquery.nestable-4f93032cfa.js

  tablesorter: &tablesorter
    - javascripts/jquery/jquery.tablesorter-2.29.0.js
    - javascripts/jquery/jquery.tablesorter.pager-2.28.8.js
    - javascripts/jquery/jquery.tablesorter.widgets-2.29.0.js

  base:
    - *jquery
    - *modernizr
    - *highlight

    - javascripts/vendor/lodash.underscore-4.17.4.js
    - javascripts/l10n.js
    - javascripts/vendor/chartist-0.11.0.js
    - javascripts/vendor/qrcode-04f46c6.js
    - javascripts/init.js

    - javascripts/vendor/select2.full-4.0.5.js

    - javascripts/studip-ui.js
    - javascripts/studip-helper-attributes.js

    - *header
    - *sidebar
    - *toolbar
    - *dialog

    - javascripts/ajax_notifications.js
    - javascripts/url_helper.js
    - javascripts/updater.js
    - javascripts/study_area_selection.js
    - javascripts/file_system.js
    - javascripts/files.js
    - javascripts/folders.js
    - javascripts/arbeitsgruppen.js
    - javascripts/news.js
    - javascripts/markup.js
    - javascripts/messages.js
    - javascripts/quick_search.js
    - javascripts/multi_select.js
    - javascripts/multi_person_search.js
    - javascripts/browse.js
    - javascripts/audio.js
    - javascripts/calendar.js
    - javascripts/schedule.js
    - javascripts/skip_links.js
    - javascripts/i18n_input.js
    - javascripts/forms.js
    - javascripts/calendar_dialog.js
    - javascripts/old_upload.js
    - javascripts/drag_and_drop_upload.js
    - javascripts/sem_classes.js
    - javascripts/cronjobs.js
    - javascripts/register.js
    - javascripts/contentbox.js
    - javascripts/dates.js
    - javascripts/tour.js
    - javascripts/questionnaire.js
    - javascripts/qrcode.js
    - javascripts/tables.js
    - javascripts/start.js
    - javascripts/responsive.js
    - javascripts/wiki.js
    - javascripts/coursewizard.js
    - javascripts/smiley.js
    - javascripts/big-image-handler.js
    - javascripts/opengraph.js
    - javascripts/actionmenu.js
    - javascripts/article.js
    - javascripts/copyable-links.js

    - javascripts/studip-selection.js
    - javascripts/studip-secure-forms.js
    - javascripts/studip-css.js
    - javascripts/studip-tooltip.js
    - javascripts/studip-scroll.js
    - javascripts/studip-selection-helper.js
    - javascripts/studip-cache.js
    - javascripts/application.js

    - javascripts/course_archive.js

    - javascripts/globalsearch.js

  raumzeit:
    - javascripts/raumzeit.js

  settings:
    - javascripts/settings.js

  tree: &tree
    - javascripts/jquery/jstree/jquery.jstree.js

  dialogs: &dialogs
    - javascripts/dialogs.js

  userfilter: &userfilter
    - *dialogs
    - javascripts/userfilter.js

  admission:
    - *userfilter
    - *tree
    - javascripts/admission.js

  enrolment:
    - javascripts/enrolment.js

  document:
    - *tablesorter
    - javascripts/document.js

  lightbox:
    - javascripts/jquery/lightbox/lightbox-2.9.0.js

  subcourses:
    - javascripts/subcourses.js

css:
  base:
    # filename : media
    studip-jquery-ui.css: screen, print
    jshighlight_tomorrow.css: screen, print
    chartist.min.css: screen, print
    style.css:  screen
    print.css:  print

  wysiwyg:
    wysiwyg.css: screen, print

  statusgroups:
    statusgroups.css: screen
  lightbox:
    lightbox.css: screen
